from http.server import BaseHTTPRequestHandler
import json, base64, smtplib, os, io
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage
import requests

# Key is read at call time to pick up Vercel env var changes
DEFAULT_GEMINI_KEY = ""

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
TO_EMAIL = os.environ.get("TO_EMAIL", "")

def build_prompt(yard_prompt, custom_notes=""):
    prompt = yard_prompt.strip() if yard_prompt else "general landscaping improvements"
    notes = f"\n\nAdditional customer notes: {custom_notes}" if custom_notes else ""
    
    return f"""You are a professional landscape designer. A customer has uploaded a photo of their yard and described what they want. Transform the yard photo according to their description.

CUSTOMER'S REQUEST: {prompt}{notes}

CRITICAL RULES:
- Keep the house, driveway, fences, and existing structures EXACTLY as they appear
- Do NOT change the perspective, angle, or lighting of the photo
- Add plants, trees, and features that look realistic, healthy, and mature
- Match the existing grass color/type and soil appearance
- Make the result look like a real photograph taken in Upstate South Carolina
- The yard should look professionally landscaped, clean, and beautiful
- If adding trees, make them appropriately sized for the space
- If adding mulch, use dark brown hardwood mulch (standard in SC)
- If enhancing lawn, make it thick, green, and freshly mowed with stripes
- Follow the customer's description as closely as possible while keeping the result photorealistic

Return the transformed image showing the completed landscaping work."""

def call_gemini(image_base64, prompt):
    """Call Gemini 2.5 Flash for image-to-image generation."""
    key = os.environ.get("GEMINI_API_KEY", DEFAULT_GEMINI_KEY)
    if not key:
        raise Exception("GEMINI_API_KEY not configured")
    
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key={key}"
    
    payload = {
        "contents": [{
            "parts": [
                {"text": prompt},
                {"inlineData": {"mimeType": "image/jpeg", "data": image_base64}}
            ]
        }],
        "generationConfig": {
            "responseModalities": ["TEXT", "IMAGE"]
        }
    }
    
    resp = requests.post(url, json=payload, timeout=90)
    data = resp.json()
    
    if "candidates" not in data:
        raise Exception(f"Gemini API error: {data.get('error', data)}")
    
    parts = data["candidates"][0]["content"]["parts"]
    result = {"text": "", "image_base64": None}
    
    for part in parts:
        if "text" in part:
            result["text"] = part["text"]
        if "inlineData" in part and "data" in part["inlineData"]:
            result["image_base64"] = part["inlineData"]["data"]
    
    return result

def send_email(name, email, phone, address, prompt_text, notes, before_base64, after_base64):
    """Send estimate request email with before/after images."""
    if not SMTP_USER or not SMTP_PASS:
        print("SMTP not configured — skipping email")
        return
    
    msg = MIMEMultipart("mixed")
    msg["From"] = f"Redwood Landscaping LLC <{SMTP_USER}>"
    msg["To"] = TO_EMAIL
    msg["Subject"] = f"🏡 Yard Visualization Request — {name or 'New Customer'}"

    yard_request = prompt_text or "(no description provided)"

    html = f"""<html><body style="font-family:sans-serif">
<h2 style="color:#2d5016">🌲 New Yard Visualization Request</h2>
<table style="border-collapse:collapse;margin:15px 0">
<tr><td style="padding:6px 12px;font-weight:bold">Name:</td><td>{name or 'N/A'}</td></tr>
<tr><td style="padding:6px 12px;font-weight:bold">Email:</td><td>{email or 'N/A'}</td></tr>
<tr><td style="padding:6px 12px;font-weight:bold">Phone:</td><td>{phone or 'N/A'}</td></tr>
<tr><td style="padding:6px 12px;font-weight:bold">Address:</td><td>{address or 'N/A'}</td></tr>
</table>
<h3>Customer's Yard Request:</h3>
<pre style="background:#f5f5f5;padding:12px;border-radius:6px;white-space:pre-wrap">{yard_request}</pre>
<h3>Additional Notes:</h3>
<p style="background:#f5f5f5;padding:12px;border-radius:6px">{notes or 'None'}</p>
<h3>Images:</h3>
<p>⬆️ <strong>Before</strong> (original yard photo — full resolution)</p>
<p>⬇️ <strong>After</strong> (AI visualization)</p>
<p style="color:#888;font-size:12px">Generated by Redwood Landscaping Yard Visualizer · <a href="https://redwood-site-jade.vercel.app">Visit Site</a></p>
</body></html>"""

    msg.attach(MIMEText(html, "html"))

    if before_base64:
        img = MIMEImage(base64.b64decode(before_base64), _subtype="jpeg")
        img.add_header("Content-Disposition", "attachment", filename="yard_before_original.jpg")
        msg.attach(img)

    if after_base64:
        img = MIMEImage(base64.b64decode(after_base64), _subtype="jpeg")
        img.add_header("Content-Disposition", "attachment", filename="yard_after_visualization.jpg")
        msg.attach(img)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.send_message(msg)

class handler(BaseHTTPRequestHandler):
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
    
    def do_POST(self):
        if self.path != "/api/visualize":
            self._respond(404, {"success": False, "error": "Not found"})
            return

        content_type = self.headers.get("Content-Type", "")
        if "application/json" not in content_type:
            self._respond(400, {"success": False, "error": "Expected JSON"})
            return

        content_length = int(self.headers.get("Content-Length", 0))
        if content_length > 4_000_000:
            self._respond(413, {"success": False, "error": "Image too large. Please use a smaller photo."})
            return

        body = self.rfile.read(content_length)
        try:
            data = json.loads(body)
        except json.JSONDecodeError:
            self._respond(400, {"success": False, "error": "Invalid request format."})
            return

        image_base64 = data.get("image", "")
        api_image = data.get("api_image", "")
        prompt_text = data.get("prompt_text", "")
        name = data.get("name", "")
        email = data.get("email", "")
        phone = data.get("phone", "")
        address = data.get("address", "")
        notes = data.get("notes", "")
        mode = data.get("mode", "generate")

        # Strip data:image prefix
        if "," in image_base64:
            image_base64 = image_base64.split(",", 1)[1]
        if "," in api_image:
            api_image = api_image.split(",", 1)[1]

        img_to_check = api_image or image_base64
        if not img_to_check:
            self._respond(400, {"success": False, "error": "No image provided."})
            return

        try:
            img_bytes = len(base64.b64decode(img_to_check))
        except Exception:
            self._respond(400, {"success": False, "error": "Invalid image data."})
            return

        if img_bytes > 7_000_000:
            self._respond(400, {"success": False, "error": "Image too large. Please use a photo under 7MB."})
            return

        try:
            if mode == "send_only":
                result = {"image_base64": api_image or image_base64, "text": "Existing visualization submitted for estimate."}
            else:
                prompt = build_prompt(prompt_text, notes)
                result = call_gemini(api_image or image_base64, prompt)

            email_sent = True
            try:
                after_img = None if mode == "send_only" else result["image_base64"]
                send_email(name, email, phone, address, prompt_text, notes, image_base64, after_img)
            except Exception as email_err:
                print(f"Email failed: {email_err}")
                email_sent = False

            response = {
                "success": True,
                "mode": mode,
                "after_image": result["image_base64"],
                "description": result.get("text", "")
            }
            if not email_sent:
                response["email_warning"] = "Visualization created but we couldn't send the estimate email. Please call us at (864) 357-4530."

            self._respond(200, response)
        except Exception as e:
            print(f"Visualization error: {e}")
            self._respond(500, {"success": False, "error": "We couldn't generate your visualization. Please try again or call us at (864) 357-4530."})
    
    def _respond(self, status, body):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(body).encode())
